### ISSUE TITLE
Exact Paths and QA Pairs for "Counter Common Sense" Subset in PhD Dataset

### ISSUE THREAD

**Issue by ShivamSRS** [jiazhen-code/IntrinsicHallu#2]
### Counter Common Sense Subset in PhD Dataset

---

I have been working with the PhD dataset [[link](https://drive.google.com/file/d/1Ex7kRqIsG2oYdl4BPIC392pxuwnwML1m/view)] provided in your IntrinsicHallu repository [[link](https://github.com/jiazhen-code/IntrinsicHallu)] and found it incredibly valuable for my research. However, I encountered some difficulty in locating a specific subset within the dataset that was mentioned in your paper [[link](https://arxiv.org/pdf/2403.11116)].

Currently, the directory structure of the dataset is organized as follows:

```
images/
    authentic/
    manipulated/
```

There is an accompanying `data.jsonl` file in the GitHub repository that provides the question-answer pairs associated with these images. The `authentic` folder contains images taken directly from the COCO 2014 validation set, while the `manipulated` folder contains images where objects, that don't belong in the image, are pasted into the original photos.

I am particularly interested in the "Counter Common Sense" subset, which, according to the paper, consists of approximately 373 images with 509 associated question-answer pairs. Unfortunately, despite manual inspection, I have not been able to locate the exact paths or locations of these images and their corresponding QA pairs within the dataset provided via the Google Drive link.

Given the substantial size of the dataset (over 7,000 images and 50,000 QA pairs), it is challenging to identify these by manual inspection. Could you please provide the exact image paths and QA pairs for the "Counter Common Sense" subset? Additionally, if possible, could you share a directory structure or list that specifically points to all images and questions in this category?

Moreover, I have also been unable to locate some of the example image-question pairs mentioned in the paper. For instance:
- The image of the cat and mouse with the question, "Which one is bigger in the image?"
- The image of the dice with the question, "Is the maximum number of points on the dice six in the picture?"

Could you please indicate where these specific examples are located within the dataset?

Your assistance with this matter would be greatly appreciated.

Thank you.

Best regards,  
Shivam Raisharma

**Comment by ShivamSRS** [comment]
In the data.jsonl file, the number of QA pairs also seem to be lesser than what is mentioned in the paper (39263 vs 53,976)

**Comment by jiazhen-code** [comment]
Hi, I've uploaded all the data. Please refer to the latest README.md for the necessary details. The data now aligns with the paper, as reflected in the most recent version on arXiv (https://arxiv.org/abs/2403.11116).
