### ISSUE TITLE
How to access the newest version of Phd dataset (especially Counter Common Sense subset)?

### ISSUE THREAD

**Issue by Hyperwjf** [jiazhen-code/IntrinsicHallu#3]
Hi! Thank you for your excellent work. I’m interested in your PhD dataset, but I’m a bit confused about how to access the latest version. According to the paper, the counter common sense images are generated by a Text2Image model. However, I noticed that the `manipulated` folder contains images with objects that don’t belong in the original photos. Could you please clarify it or update the dataset?

**Comment by jiazhen-code** [comment]
Hi, I have uploaded all the data. You can check the latest readme.md to obtain the data you need.
